### PR TITLE
fix(cleanup): Consolidate the duplicate code in Properties, PropsGump, and PropsConfig 

### LINKED ISSUE #534: [Cleanup] Consolidate the duplicate code in Properties, PropsGump, and PropsConfig
- Consolidate PropsConfig and everything that uses it.
- Consolidate the type checking in Properties and PropsGump
- use AggressiveInlining where possible
- Breakout the `Exception` classes in Properties.cs to their own file

### PR DESCRIPTION
**Pull request by kamronbatman**
Closes #534 

Thank you @immaciek!

### CODE REVIEW

**Comment by kamronbatman** [comment]
I had issues while testing this, so I gotta go back and fix it. I can't remember what, I but iirc, I broke something. Been a long week.

**Comment by immaciek** [comment]
> I had issues while testing this, so I gotta go back and fix it. I can't remember what, I but iirc, I broke something. Been a long week.

I'm quite curious what exactly you were testing that failed?

File: Projects/UOContent/Engines/Spawners/SpawnPropsCommand.cs [hunk 1]
```diff
@@ -61,7 +62,7 @@ private class InternalTarget : Target
             protected override void OnTarget(Mobile from, object targeted)
             {
                 var type = targeted.GetType();
-                if (!Add.IsEntity(type))
+                if (IsEntity(type))
```
Comment (kamronbatman) [inline Projects/UOContent/Engines/Spawners/SpawnPropsCommand.cs:65]: This should be: `if (!IsEntity(type))`
