### PR TITLE
fix: Fixes character starting cities.

### LINKED ISSUE #1408: limit new haven to pub 16
Creating a character on a pre Renaissance server take it to haven.

### PR DESCRIPTION
**Pull request by kamronbatman**
### Summary

- Moves starting city info from AccountHandler to CharacterCreation
- Simplifies the logic of determining the starting cities
- Adds support for Trammel & Felucca for non-young accounts
- Fixes fall through starting city for v6+ in UOR era.
- All staff are force-sent to GA.

### TODOS

- Move the starting cities to JSON files
- Add in New Magincia (`1075077`) to the client versions/eras that support it.

Closes #1408

### CODE REVIEW

File: Projects/UOContent/Misc/CharacterCreation.cs [hunk 1]
```diff
@@ -76,8 +76,111 @@ public static class CharacterCreation
...
+        }
+
+        if (feluccaAvailable)
+        {
+            Array.Copy(FeluccaStartingCities, 0, cities, index, FeluccaStartingCities.Length);
+        }
+
+        // TODO: Add Royal City for gargoyles
+
+        if (cities.Length == 0)
```
Comment (blendax78) [inline Projects/UOContent/Misc/CharacterCreation.cs:177]: Should this be moved up to line 161, and maybe have a return statement if `cities.length == 0`?  Just wondering if there are no cities available, do we need to do the Array.Copy?  Also, will it cause issues if (somehow) TrammelStartingCities.length? == 0 AND FeluccaStartingCities.Length == 0, and we try to do the Array.Copy??

Comment (kamronbatman) [reply Projects/UOContent/Misc/CharacterCreation.cs:177]: Yeah good call! - And yeah, it will cause issues, hence the warning. Specifically, players won't be able to log in. We don't want to send them to a map that isn't available, for whatever reason. So we either have to crash, or throw a warning/error.

Thoughts on other options?

Comment (blendax78) [reply Projects/UOContent/Misc/CharacterCreation.cs:177]: ahh ok.  Yeah, I can't really think of any other good way to handle that.  Like you said, throwing a warning/error is probably the best bet

**Review by blendax78 — COMMENTED** [review]
💯 awesome

**Comment by mdodkins** [comment]
Looks good :+1:
