### PR TITLE
fix: Moves many EventSinks out of core.

### LINKED ISSUE #1782: Remove unneeded EventSinks
- HungerChanged => Can be turned into an override in Mobile.cs (public virtual void OnHungerChanged(int oldValue))
- OpenSpellbookRequest
- CastSpellRequest
- BandageTargetRequest
- RenameRequest
- ProfileRequest
- ChangeProfileRequest
- DeleteRequest
- PlayerDeleted
- GuildGumpRequest
- QuestGumpRequest
- ClientVersionReceived
- EquipMacro
- UnequipMacro
- TargetSkillUse
- TargetedSpell
- OpenDoorMacroUsed
- AnimateRequest

### PR DESCRIPTION
**Pull request by paezao**
Closes #1782

### CODE REVIEW

File: Projects/UOContent/Accounting/AccountHandler.cs [hunk 1]
```diff
@@ -228,7 +230,11 @@ private static void EventSink_DeleteRequest(NetState state, int index)
 
                 m.Delete();
 
-                EventSink.InvokePlayerDeleted(m);
+                StaminaSystem.OnPlayerDeleted(m);
```
[the remark this answers is not in the document]
Comment (paezao) [reply Projects/UOContent/Accounting/AccountHandler.cs:233]: That would be cool for sure, I dont know any but will research

File: Projects/UOContent/Spells/Ninjitsu/AnimalForm.cs [hunk 2]
```diff
@@ -64,7 +64,6 @@ public AnimalForm(Mobile caster, Item scroll) : base(caster, scroll, _info)
 
         public static void Initialize()
```
Comment (kamronbatman) [inline Projects/UOContent/Spells/Ninjitsu/AnimalForm.cs:65]: Let's remove empty Initialize (or Configure)

File: Projects/UOContent/Special Systems/Engines/PreventInaccess.cs [hunk 3]
```diff
@@ -32,15 +32,12 @@ public static class PreventInaccess
...
-
-            if (Enabled)
-            {
-                EventSink.Login += OnLogin;
-            }
         }
 
         public static void OnLogin(Mobile from)
         {
+            if (!Enabled) return;
```
Comment (kamronbatman) [inline Projects/UOContent/Special Systems/Engines/PreventInaccess.cs:39]:
```suggestion
            if (!Enabled)
            {
                return;
            }
```
